# Generated by Django 3.0.2 on 2020-03-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input1', models.IntegerField()),
                ('input2', models.IntegerField()),
                ('input3', models.IntegerField()),
                ('timestamp', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
