# Generated by Django 3.0.2 on 2020-03-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='label1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracker',
            name='label2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracker',
            name='label3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
