# Generated by Django 3.0.2 on 2020-03-24 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200324_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='tracker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Tracker'),
            preserve_default=False,
        ),
    ]
